### PR TITLE
app: add checkout process

### PR DESCRIPTION
**Pull request by BacLuc**
Issue: #13

### CODE REVIEW

**Comment by BacLuc** [comment]
Tests are still missing

**Review by Off3line — APPROVED** [review]

**Comment by Off3line** [comment]
I still suggest merging now despite missing tests, what do you think?

**Comment by BacLuc** [comment]
> I still suggest merging now despite missing tests, what do you think? 

If we dont need the funcionality now, i would rather write the Tests before merging

**Comment by Off3line** [comment]
> > I still suggest merging now despite missing tests, what do you think?
> 
> If we dont need the funcionality now, i would rather write the Tests before merging

Agreed

**Pull request closed without merging**
